<?php

/**
 * Implements hook_registry_files_alter().
 */

function mobile_detect_registry_files_alter(&$files, $modules)
{
  $library_path = _mobile_detect_get_library_path();

  $files[$library_path . '/Mobile_Detect.php'] = array(
    'module' => 'mobile_detect',
    'weight' => 0,
  );
}

/**
 * Getter function to retrieve a Mobile_Detect() singleton for
 * the current page request, utilizing static caching
 */
 
function mobile_detect_get_object()
{
  $detect = &drupal_static(__FUNCTION__);

  if (!isset($detect)) {
    try {
      $detect = new Mobile_Detect();
    } catch (Exception $e) {
      $detect = NULL;
      watchdog('mobile_detect', 'Could not create a Mobile_Detect() object: %message', array('%message' => $e -> getMessage()), WATCHDOG_ALERT);
    }

  }

  return $detect;
}

/**
 * Retrieve the path to the Mobile_Detect library; will use Libraries API if detected.
 */

function _mobile_detect_get_library_path()
{
  if (function_exists('libraries_get_path')) {
    $library_path = libraries_get_path('Mobile_Detect');
    if (! $library_path) $library_path = 'sites/all/libraries/Mobile_Detect';
  } else {
    $library_path = 'sites/all/libraries/Mobile_Detect';
  }
  
  return $library_path;
}
